open-AIMS/ADRIA.jl

Aviz/src/analysis.jl, src/ADRIA.jl, src/analysis/analysis.jl, src/analysis/sensitivity.jl, src/metrics/sensitivity.jl
Adds regional analyses of sensitivity and outcomes.
Given inputs (`X`) and corresponding outputs (`y`):
```julia
rsa_analysis = ADRIA.sensitivity.rsa(X, y)
foi = [:SRM, :fogging, :a_adapt]
rule = y -> all(y .> 0.5)
roa = ADRIA.sensitivity.outcome_map(X, y, rule, foi)
```
See included docstrings for details, but in the rough indicative plot below we see scenario outcomes increase linearly with an increase to factors 1, 3, 6. 
Higher outcomes are seen with low values of Factor 2, which otherwise appears non-influential.
x-axis indicates the upper bin edge
y-axis is the normalized outputs
Next step is to simplify use so that users only have to provide the ResultSet alongside specific options for the analysis.
The same process can then be wrapped to produce plots.
Closes #257
=> Add support for Regional Sensitivity Analysis (RSA)

src/Domain.jl
Uses Haversine distance instead of Euclidean.
Also addressed incorrect parameter order, as the function requires x, y (i.e., long, lat).
Closes #236
=> Fix: calculate distance between sites

src/Domain.jl, src/ecosystem/Ecosystem.jl, src/utils/text_display.jl
Relying on ModelParameters or DataFrames for the output slows the first time display quite a bit (can be minutes)
=> Simplify display of model spec

src/Domain.jl, src/io/inputs.jl, src/sites/connectivity.jl
Initial call to `load_domain()` is very slow (~30secs), largely due to the initial call to the CSV.jl package (and the number of connectivity files being read in).
This PR adjusts the data loading process so fewer allocations are made, and adds additional type information to improve readability, to reduce the initial precompilation load.
=> Reduce allocations in `load_domain()`

src/ecosystem/Ecosystem.jl, src/io/sampling.jl
Something I missed when reviewing #290 - generated samples have to be adjusted such that `dist_thresh` is set to 0 when `use_dist` is set to 0.
=> Adjust samples when use of distance thresholds is turned off

src/metrics/metrics.jl, src/scenario.jl
Removed hardcoded position indexers to make the metric more generic with regard to the number of coral groups/size classes represented.
This PR also takes the opportunity to remove dependence on DataFrames (which are quite slow and heavy to use for this) and instead uses NamedDimsArray as much as possible.
Note: This PR also includes a fix to produce shelter volumes in m^3 / m^2
Previous implementation applied a log10-log10 relationship, as opposed to a natural log-log relationship
=> Adjust shelter volume to remove hardcoded index and leverage NamedDimsArray

src/io/sampling.jl
Allow users to easily fix factors in place (i.e., make them constant).
Note: No resetting is offered yet as what it means for a user to "reset" a domain/model is not entirely clear (revert everything including "sim constants"? Revert just the fixed factors?
For now, if the user wants to start fresh they can simply reload the domain.
=> Add capability to fix factors in place

examples/site_selection.jl, src/sites/dMCDA.jl, test/site_selection.jl
Closes #308, where the storage NamedDimsArray for ranks in `run_site_selection()` was set to n_site_int instead of n_sites (which did not throw an error in tests because the filtered example site set has 5 sites).
Also adds proper indexing for site storage which accounts for filtered sites.
=> Correct issue with size of NamedDims array for storing ranks in `run_site_selection()`

src/io/result_io.jl, src/scenario.jl
`site_area()` may be calculated or stored differently based on model or approach so use the function instead of accessing the attribute/field directly.
=> Replace use of area attribute/field with call to function `site_area()` to ensure correct values

src/io/sampling.jl
Remove attempted access to non-existent fields when setting all factors to their default values
=> Remove reference to defunct fields when making factors constant

ext/AvizExt/viz/sensitivity.jl
Previously was taking unique index values to avoid duplicate x-tick labels, but it leads to a mismatched number of elements causing plotting to error.
We'll just live with duplicate value labels along the x-axis for now.
=> Address mismatched number of elements under certain conditions

src/ADRIA.jl, src/ecosystem/Ecosystem.jl, src/sites/dMCDA.jl
Closes #357
Copras method was causing issues due to giving all NaNs for the criteria scores, so that rankings were meaningless. On further research it seems the Copras method is a weighted linear combination of the score for criteria to be maximised divided by the maximum criteria score and score for criteria to be minimised divided by minimum criteria score. It seems that maybe because ADRIA only has maximising criteria this was giving NaN scores (all other methods were found to not error with the same decision matrix and the error occured for any decision matrix with the Copras method). To fix this issue, Copras is removed from the available set of methods in this PR.
All other methods were tested for their outputs  to verify that they should not error (given reasonable decision matrix …
=> Remove Copras method due to erroring

src/io/ResultSet.jl, src/io/sampling.jl, src/metrics/metrics.jl, src/metrics/scenario.jl
Errors get thrown when collecting metrics on a single simulation, as when running a set of scenarios for robustness analysis.
=> Fix: Metric errors when applied to a single simulation

ext/AvizExt/theme.jl, ext/AvizExt/viz/scenario.jl
Corrects bug where color weight was being incorrectly calculated, and adds a density plot alongside the scenario trajectories.
Also updated the colors to use the preset color scheme.
=> Update scenario viz

src/io/result_io.jl, src/scenario.jl, src/utils/setup.jl
When running  `run_scenarios` passing multiple RCPs as arguments, it was creating one dataset folder for each RCP and then consolidating at the end. Now it only creating one folder, once, and skipping the consolidation step. Close #342.
=> Refactor run_scenarios to improve when running multiple rcps

src/scenario.jl
The current ode solver is a BS method, which is an adaptive timestep 3rd order RK method. Adaptive timesteps can reduce efficiency in non-stiff ode solutions. Aditionally, higher order solvers are less efficient if there is neglible trade off in accuracy. Due to this fixed timesteps of varying precision with the lower order Euler scheme were investigated.
Timesteps of size 1/10,1/5, 1/3 and 1/2 were investigated with the Euler solver and the timings and RMSE in comparison to the original solver were compared.
Plot of average time for just the ode solver for 100 timesteps with 200 samples:
Plot of total time for 256 ADRIA scenarios for each solver:
Plot of RMSE between the original and Euler solvers:
=> Changes to ode solver and time step for efficiency improvements

src/scenario.jl
Sorry to do a final PR for this - I forgot to add the 'adaptive=false` to specify a non-adaptive scheme. Also, the tolerances aren't used for non-adaptive schemes so they can be removed.
To confirm, the previous timings and RSMEs were compared for adaptive and non-adaptive schemes, I just forgot to add the flag in the final PR.
=> Add `adaptive=false` specification and remove tolerances

src/scenario.jl
Had a cross-eyed moment and was using wave condition for the previous timestep instead of the current timestep when adjusting DHWs. This PR corrects this bug.
=> Fix bug: Use wave condition for current timestep, not previous

src/metrics/site_level.jl
`per_loc` was being called instead of `loc_trajectory`
@Zapiano this may have been the cause of the error we saw the other day.
=> Incorrect function being called

src/interventions/seeding.jl, src/scenario.jl
Batch sizes seem to lead to issues with values being overwritten with cache matrices when using threads within parallel runs.
This PR also includes some miscellaneous changes (updating comments, removing dead code, etc).
=> Remove use of batch sizes when running parallel scenarios

ext/AvizExt/viz/spatial.jl
Small bug introduced in #382 which broke plotting of spatial domain (overly specific type constraints).
Took the opportunity to update the default colorbar label as well, which was incorrect.
```julia
dom = ADRIA.load_domain("some domain")
ADRIA.viz.map(dom)
```
=> Fix map display (default display when plotting Domain or ResultSet)

src/ecosystem/corals/growth.jl, src/scenario.jl
Closes #405 
Includes a number of changes to avoid Julia kernel crashing when running a high number of scenarios.
- Only uses `pmap` in workloads that require multiprocessing, otherwises uses `map`
- Does not create a reusable cache structure when using multiple cores (but does for single core workloads)
- Explicit use of `CachingPool()` to avoid re-serialization of data structures to workers (default behavior in upcoming Julia v1.10 release)
- Forces garbage collector (gc) to run if 95% of available memory is in use. Forcing the gc to run too often can increase runtimes and lead to other issues so I've opted to only run this when absolutely needed
In addition to the above, a key change resolving crashes in multi-processing contexts was (circa L 271 in `scenarios.jl`):
```julia …
```
=> Fix excessive memory use (#405)

src/ecosystem/corals/Corals.jl, src/ecosystem/corals/growth.jl, src/interventions/seeding.jl, src/io/ResultSet.jl, src/io/result_io.jl, src/scenario.jl, test/seeding.jl
Adjusting representation of natural adaptation and heritability based on feedback and discussion (thanks to @ecolology), principally:
Minimum bound of truncated distribution for each size class is the minimum of the Mixture distribution, such that over time corals are less likely to die from low DHW events. This makes the (truncated) normal distribution behave somewhat more like a log-normal distribution.
**Note: the CDF above is prior to any adjustments based on depth. Actual mortality may be significantly less**
Standard deviation is now fixed to the original value used for a given size class. Standard deviations does still change over time (we see an increase) due to the Mixture and truncation approach, indicating a greater variability in DHW sensitivity over time.
The +20 from mean …
=> Adjustments to heritability based on feedback

ext/AvizExt/viz/sensitivity.jl
Figure would be unnecessarily squashed when plotting outcome mapping results for a single factor.
```julia
dom = ADRIA.load_domain("... some domain ...")
scens = ADRIA.sample(dom, 1024)
rs = ADRIA.run_scenarios(scens, dom, "45")
s_tac = ADRIA.metrics.scenario_total_cover(rs)
μ_stac_2050 = vec(mean(s_tac(timesteps=2045:2055, scenarios=:), dims=1))
foi = ["guided"]
rule = y -> all(y .> 0.5)
om = ADRIA.sensitivity.outcome_map(rs.inputs, med_stac_2050, rule, foi; S=20, n_boot=100, conf=0.95)
ADRIA.viz.outcome_map(rs, om, foi; axis_opts=Dict(:title => "Test"))
```
Before:
After:
=> Fix unnecessarily squashed figure when plotting outcome map for 1 factor

src/analysis/clustering.jl, src/analysis/rule_extraction.jl
- The function target_cluster was moved from rule_extraction.jl to time_series_clustering.jl, which makes more sense
- It now returns vector identifying scenarios that belong to target cluster instead of the target cluster index
- It now merges the best cluster with the second one if the number of scenarios inside it is below some threshold
Closes #423 .
=> Move and modify behaviour of target_cluster function

src/ADRIA.jl, src/ecosystem/corals/growth.jl, src/interventions/seeding.jl, src/io/result_io.jl, src/scenario.jl, src/utils/setup.jl, test/seeding.jl
Closes #413 and re-addresses #405.
Previous approach to parallel runs first initialized the provided domain object with environmental data (via `switch_RCPs!()`).
The `domain` was then sent to workers for each scenario run.
This had two effects:
1. For each run the domain object would be serialized and sent to workers, which unserialized the data on receipt to begin its workload. Due to the size of the domain data, this caused significant overhead
2. Because an explicit copy of the domain is not sent to each worker, I suspect each worker received a reference to the original data structure (although the data associated with the struct would be a copy).
Because of the above, Julia's garbage collector (GC) would recognise the Domain as still in use after a worker had finished a run, so it …
=> Fix workers crashing and leaking memory when running scenarios in parallel

src/metrics/scenario.jl
Some scenario metrics were returning a Matric object with a field `:scenario` instead of `:scenarios`, which was raising some errors.
=> Fix scenario metrics with field :scenario instead of :scenarios

src/decision/dMCDA.jl, src/ecosystem/corals/growth.jl, src/interventions/seeding.jl, src/scenario.jl
Previous implementation assumed localised coral reproduction when incorporating DHW tolerances. This was simply for convenience, to have a prototype working.
This PR incorporates coral larvae from other (source) locations that settle on to a given (sink) location.
The role of connectivity between locations are then better represented as locations with a higher thermal tolerance can contribute larvae to locations with less thermal tolerance (and vice versa).
=> Incorporate settler DHW tolerances

src/metrics/metrics.jl
Previous approach was to naively calculate the relative  (to $k$) area for all locations using the disk-based Zarr data. This change loads all data into memory and only calculates relative cover for non-zero locations.
The caveat re performance is that much larger spatial areas may take a bit longer to initially load.
=> Address very slow extraction of relative cover values

ext/AvizExt/viz/clustering.jl, ext/AvizExt/viz/spatial.jl
`ADRIA.viz.map` has a call to `per_loc` that is raising an error because it doesn't have a `:scenarios` dimension. This is fixed by computing the summary statistics for this particular case inside `map` function.
=> Fix clustering map visualisation

src/metrics/site_level.jl
`loc_trajectory` and `per_loc` calls to `dim` are raising a `not defined` error. The fix for this is to qualify these calls with `NamedDims.dim` 
Closes #427
=> Fix loc_trajectory and per_loc function 

src/analysis/rule_extraction.jl
SIRUS package recently changed its main component type from StableRules{Float64} to StableRules{Int64} and this need to be update at our code as well.
Ref: https://github.com/rikhuijzer/SIRUS.jl/pull/46
=> Update SIRUS StableRules type

docs/make.jl, docs/src/API.md, docs/src/architecture/architecture.md, docs/src/architecture/domain_and_resultsets.md, docs/src/usage/analysis.md, docs/src/usage/domain.md, src/metrics/metrics.jl, src/metrics/reef_indices.jl, src/metrics/scenario.jl
This PR includes/adds a cookbook page and uses a workaround to include documentation for metrics which use the `Metric` type.
As a bonus, the updated approach to defining metrics makes the docstring available for the built-in Julia help system.
I've noted that documentation for metrics are often incomplete or inconsistently defined. This will be addressed in a later PR.
=> More updates to documentation

ext/AvizExt/analysis.jl, src/analysis/sensitivity.jl
Use views to reduce memory allocations / data copying
Use `@floop` to calculate $S$ for each factor using threads
Example (spacing added for readability):
```julia
julia> @time begin
n = 8192 * 8
X = rand(n, 3)
@info "Size of X:" size(X)
results = NamedDimsArray(X[:, 3], scenarios=1:n)
ADRIA.sensitivity.pawn(X, results, ["dummy1", "dummy2", "real1"])
end
┌ Info: Size of X:
└   size(X) = (65536, 3)
0.153640 seconds (1.06 k allocations: 89.405 MiB, 22.54% gc time)
2-dimensional NamedDimsArray(KeyedArray(...)) with keys:
↓   factors ∈ 3-element Vector{Symbol}
→   Si ∈ 6-element Vector{Symbol}
And data, 3×6 StaticArraysCore.MMatrix{3, 6, Float64, 18} with indices SOneTo(3)×SOneTo(6):
(:min)     (:mean)    (:median)  (:max)     (:std)     (:cv)
(:dummy1)   0.52819    0.696462   0.726732 …
```
=> Changes to improve performance of PAWN sensitivity analysis

src/analysis/rule_extraction.jl
Instead of checking if a clause second element was :L or :R, it was checking the whole clause. which was always false. That was causing the prints to always use the "greater than or equal" for all clauses.
=> Fix print_rules condition

src/analysis/sensitivity.jl
Say a user was assessing the mean of some scenario outcome
```julia
μ_tac = mean(ADRIA.metrics.scenario_total_cover(rs), dims=:timesteps)
ADRIA.sensitivity.pawn(rs, μ_tac)
```
Previously, this would fail with an error as `μ_tac` would be a matrix (i.e., $1 \times N$) rather than a vector which the method expects.
The change also supports transposed matrices:
```julia
μ_tac = mean(ADRIA.metrics.scenario_total_cover(rs), dims=:timesteps)'  # note the transpose!
ADRIA.sensitivity.pawn(rs, μ_tac)
```
The above `μ_tac` would be an $N \times 1$ matrix (again, instead of a vector).
The PR supports implicit conversion to vector simply for convenience.
Originally, the user was expected to convert to vector explicitly prior to use:
```julia
μ_tac = vec(mean(ADRIA.metrics.scenario_total_cover(rs), …
```
=> Adjust PAWN function to support 1D matrix for convenience

src/metrics/performance.jl, src/metrics/reef_indices.jl
Stopgap update to coefficients used for the Reef Tourism Index metric.
Notes from Ryan:
Note the coral juveniles coefficient is not significant. The overall model fit isn’t great either – 13.4% R-squared. 
This is a very ad-hoc solution for the tourism indicator until something better is thought of.
=> Update Reef Tourism Index regression coefficient (temporary solution)

ext/AvizExt/viz/spatial.jl
Add option to mapping to show management zones (defaults to false.
```julia
ADRIA.viz.map(dom; opts=Dict{Symbol,Any}(:show_management_zones=>true))
```
Awkward dictionary-based option setting needs to be addressed somehow.
Specifying the types in the dictionary is necessary, otherwise Julia tries to optimize by restricting the Dict only to `Symbol=>Bool` pairs, which causes an issue when other options with different types get set (such as `Symbol=>String`).
=> Add option to show GBRMPA management zones

src/decision/dMCDA.jl
In certain cases it seems the MCDA is selecting locations with no available space for seeding deployments.
This PR ensures such locations are removed from consideration.
=> Remove locations with no space from consideration for interventions

docs/src/usage/analysis.md, ext/AvizExt/viz/clustering.jl, src/analysis/clustering.jl, src/viz/viz.jl, test/clustering.jl
Those two functions names were not according to blue style guide and were not very meaningful (in particular `ts_cluster`). We should have functions whose names tell "what they do" (like `cluster_series`) or what they return (like `clustered_scenarios`).
=> Rename time_series_clustering and ts_cluster

src/Domain.jl, src/ExtInterface/ADRIA/Domain.jl, src/ExtInterface/ReefMod/Domain.jl
Closes #483
Ensures k area (coral carrying capacity for each location) is loaded as a non-dimensional value indicating the proportion of absolute location area.
As a consequences, we can simplify/remove the `site_k()` interface methods.
=> Consistent treatment of k area on data load

src/Domain.jl, src/ExtInterface/ReefMod/Domain.jl, src/io/inputs.jl, src/scenario.jl
Closes #484
Loads initial coral cover (icc) data in a more consistent way. 
`icc` is always provided in values relative to absolute area, but on load, it gets transformed to be relative to k area instead.
=> Transform ICC from relative to absolute area to relative to k area

src/ADRIA.jl, src/Domain.jl, src/ecosystem/corals/growth.jl, src/interventions/seeding.jl, src/scenario.jl, test/growth.jl, test/runtests.jl
As in title.
Note: initial coral covers are still being converted from values relative to absolute area.
Part of #480 (Current item 2 - " Scenario running methods to be refactored to expect only values relative to area")
=> Adjust `run_model()` to only require values relative to $k$ area

ext/AvizExt/viz/sensitivity.jl, src/analysis/sensitivity.jl
Resolves issue #440.
Previously, plotting factors where the splitting of the factor domain had uneven steps (due to rounding used to define mapping labels possibly), duplicate values would arise when creating the x-axis for outcome mapping plots (see issue). 
Previously plots of factor with uneven splitting would look like this:
with duplicate x-values.
Current plots now look like this:
without duplicate x-values.
=> Fix duplicate x-axis values bug in `viz.outcome_map()`

.gitignore, Project.toml, ext/AvizExt/viz/clustering.jl
- Updated functions _clusters_colors and _cluster_color to _get_colors and _get_alphas
- Added return type to all functions in this file
- Adapted the whole file to the style guide
There is an option to fill or not the area inside the confidence interval - the best visualization option may depend on the situation. The default value of `:fill_confint` is currently set to `true`:
This is how it looks with `:fill-confint` set to `false`:
Closes #464
=> Update viz.clustered_scenarios to allow confidence interval plot

ext/AvizExt/viz/viz.jl
Prevent missing last label if (length(labels) - 1) is not multiple of label_step.
Here are some examples plotting `ADRIA.metrics.total_absolute_cover(rs)[timesteps=1:last_year]` for different values of `last_year`. I have clustered scenarios, targeted, and I am plotting using `ADRIA.viz.clustered_scenarios()`:
| last_year = 26 |  last_year = 27 |
|----------------|-----------------|
| ![tac_outcome_series_26](https://github.com/open-AIMS/ADRIA.jl/assets/8040719/b903c45c-5507-4466-8e39-85f1ddd2038a) | ![tac_outcome_series_27](https://github.com/open-AIMS/ADRIA.jl/assets/8040719/46e864c6-6e29-40b6-9ceb-c63c8d2d7e46) |
| last_year = 28 | last_year = 29 |
|----------------|----------------|
|![tac_outcome_series_28](https://github.com/open-AIMS/ADRIA.jl/assets/8040719/f453921b-4494-4534-bd39-4 …
=> Fix _time_labels missing last label

src/ecosystem/Ecosystem.jl
Error occurs due to incorrect input type for EnvironmentalLayer. This PR adds Missing to possible input types in EnvironmentalLayer
Resolves issue #510 .
=> Fix bug causing Domain loading with RCP to error

ext/AvizExt/viz/clustering.jl, ext/AvizExt/viz/scenarios.jl, ext/AvizExt/viz/viz.jl, src/analysis/analysis.jl
When it is `true`, `scenarios` plot the confidence intervals together with the median for each scenario type (guided, unguided and counterfactual). It defaults to `true`.
| :summarize = true | :summarize = false |
|-------------------|--------------------|
| ![tac_scenarios_true](https://github.com/open-AIMS/ADRIA.jl/assets/8040719/30169704-4402-4305-93a6-b49bf8f33961) | ![tac_scenarios_false](https://github.com/open-AIMS/ADRIA.jl/assets/8040719/ec8730a1-eb4f-41c6-a8e2-7dc784e524e1)|
=> Add `:summary` option to `viz.scenarios`

ext/AvizExt/theme.jl, ext/AvizExt/viz/clustering.jl
These were partially supported before, but this implements a few improvements like:
- Allow passing a BitVector of clusters
- Move some common functions to theme.jl
- When plotting a BitVector cluster, use "Target" and "Non-Target" as legend labels
Close #494
=> Add support series and map binary clusters plots

ext/AvizExt/AvizExt.jl, ext/AvizExt/theme.jl, ext/AvizExt/viz/clustering.jl, ext/AvizExt/viz/scenarios.jl, ext/AvizExt/viz/viz.jl, src/analysis/analysis.jl, src/analysis/scenario.jl
As in title.
Because this issue involved changing viz.scenarios code, that had a lot code duplicated from viz.clustered_scenarios, also refactored both to re-use the same functions.
Following are some plotting results: 
- scenario_total_cover
| scenario_total_cover :summarized = true | scenario_total_cover :summarized = false|
|--|--|
|![scenarios__summarize_true](https://github.com/open-AIMS/ADRIA.jl/assets/8040719/52c37ad5-fea7-469c-89cc-f6607a590c35)|![scenarios__summarize_false](https://github.com/open-AIMS/ADRIA.jl/assets/8040719/8face8b0-1930-4b98-b94f-06c07da65185)|
- scenario_total_cover with the filter `target_scens = (rs.inputs.guided .== 0) .& (rs.inputs.SRM .< 1.0)`
| :summarized = true | :summarized = false|
|--|--|
|![scenarios_filtered__summarize_true](https://github.com/ope …
=> Fix scenarios subsetting now working

Project.toml, ext/AvizExt/viz/sensitivity.jl, src/Domain.jl, src/ExtInterface/ADRIA/Domain.jl, src/analysis/analysis.jl, src/analysis/sensitivity.jl, src/decision/Criteria.jl, src/ecosystem/Ecosystem.jl, src/interventions/Interventions.jl, src/io/inputs.jl, src/io/result_io.jl, src/io/sampling.jl
In `sensitivity.outcome_map()` factor splittings are determined using the number of bins provided and the function `quantile()` from the Statisitcs.jl package. This is an issue for categorical functions as `quantile()` treats the lowest and highest values in the set of samples provided as the upper and lower bounds of the splitting. This means, with the number of bins being equal to the number of categories, there are duplicate values because there are not enough splittings for the number of categorical variables. Providing the number of bins as (number of categories) +1 does not solve this either because quantile tries to split the range of values into smaller splittings without adjusting the upper and lower bounds. 
The fix provided here checks whether the variable is categorical and if …
=> Fix bug in how `sensitivity.outcome_map()` treats categorical variables.

docs/src/usage/cookbook.md, examples/site_selection.jl, ext/AvizExt/viz/scenarios.jl, src/decision/dMCDA.jl, src/decision/location_selection.jl, src/ecosystem/Ecosystem.jl, src/ecosystem/connectivity.jl, test/mcda.jl, test/site_selection.jl
Addresses issue #324
- adds 3 aggregation functions for ranks outputs
- ranks can be taken in as result set for ADRIA runs outputs or as ranks NamedDimsArray from run_site_selection()
- 3 functions for calculating location selection frequencies 
- location_selection_frequencies() counts frequency with which sites are actually selected (ranks 1-5)
- ranks_to_frequencies() counts frequencies with which each site is selected for each rank.
- ranks_to_frequencies_ts() calculates the same but for each time step.
- ranks_to_location_order() gives the ranking order as location names for each scenario (no time dependent version).
- Other changes fix bugs in run_site_selection() due to upstream changes.
=> Adds a series of aggregation functions for location selection ranks

src/Domain.jl, src/ExtInterface/ReefMod/Domain.jl, src/ecosystem/connectivity.jl, src/ecosystem/corals/growth.jl, src/interventions/seeding.jl, src/io/result_io.jl, src/scenario.jl, test/seeding.jl
Attempt to reduce high number of memory allocations to a more manageable level 
(recalling that memory allocations are not the same as memory use - although a small reduction is a nice side-effect here).
Much of the effort is in streamlining the `settler_DHW_tolerance!()` function.
High memory use is somewhat expected in GBR-scale simulations (3806 reefs).
Currently, `settler_DHW_tolerance!()` is doing a naive check for any locations with $k$ > 0 - and it turns out all represented reefs have $k$ > 0.
Note: Please ignore changes to `settler_cover()` - I had to cherry pick some changes from another branch (for turning all calculations to be relative to $k$ area) and these were brought over by accident. The changes there don't affect anything.
=> Resolve Out-of-Memory issues when working with larger spatial areas

src/ecosystem/Ecosystem.jl, src/io/result_io.jl
The column indicating the RCP was originally the first entry but can be the first or last column depending on how/who the scenario spec was generated (and what version of ADRIA).
Remove the assumption that the RCP column is before any other discrete-valued parameter.
Fixed a bug where values set as constants by the user were being floored as well.
Closes #518
=> Avoid assuming where the RCP column is when adjusting scenario spec

src/decision/location_selection.jl
Closes #562
A dims reference in `location_selection_frequency()` was incorrect. This has been changed to a symbol to avoid any future issues.
=> Fix integer dims reference in location_selection_frequency()

docs/src/usage/scenario_generation.md, src/decision/Criteria.jl, src/interventions/Interventions.jl, src/io/sampling.jl, test/sampling.jl
`fix_factor_bounds!()` adjusts the sampling bounds of a specified factor. Currently the function checks against the previously set values to make sure the range is meaningful. This means the domain needs to be reloaded if the requested new interval is larger than the previous altered one. Alternatively, a new parameter called `:default_bounds` could be added to the Param type and used to check the new bounds are meaningful (e.g. criteria weights are between 0 and 1, no negatives etc.).
=> Add function to alter sampling bounds on parameters to specified value.

test/runtests.jl
As in title.
The way it was, every time we run `include("test\\runtests.jl")` a tmp folder was being created inside `test\data` and was not being deleted.
=> Prevent test_rs() from creating tmp dir inside test/data

Aviz/build/precompile_script.jl, Project.toml, docs/src/usage/analysis.md, ext/AvizExt/AvizExt.jl, ext/AvizExt/viz/sensitivity.jl, ext/AvizExt/viz/spatial.jl, ext/AvizExt/viz/viz.jl
GLMakie may be preferred when creating visualizations locally, but allows WGLMakie to be installed instead for web/browser-based plots.
By default, figures will appear in the VS Code plot pane:
To switch backends, either:
```julia
] remove GLMakie
] add WGLMakie
```
or have both installed and activate the desired backend:
```julia
using WGLMakie
WGLMakie.activate!()
using GLMakie
GLMakie.activate!()
```
https://docs.makie.org/stable/explanations/backends/
=> Visualizations to be agnostic to Makie backend

ext/AvizExt/theme.jl, ext/AvizExt/viz/clustering.jl, src/analysis/scenario.jl
Closes #549.
With normal clusters
With target/non-target clusters - here I just generated a `rand(Bool, length(clusters))`:
=> Fix plot map

src/scenario.jl
Recent version requires use of named arguments:
```julia
@showprogress desc=run_msg dt=4 ...
```
Otherwise a deprecation warning is thrown:
```julia
┌ Warning: `Progress(n::Integer, desc::AbstractString, offset::Integer = 0; kwargs...)` is deprecated, use `Progress(n; desc = desc, offset = offset, kwargs...)` instead.
│   caller = ip:0x0
└ @ Core :-1
```
=> Update use of progress meter to resolve deprecation warning

ext/AvizExt/viz/sensitivity.jl, src/decision/dMCDA.jl, src/interventions/Interventions.jl, test/site_selection.jl
Replace consts with a function to allow flexibility. Previously modifying the list of supported methods required Julia to be restarted as the method list was assigned to a const.
Rather than listing out methods to ignore, we now explicitly list out the methods to include. This avoids situations where new (unsupported) methods are added to JMcDM.
Tests pass locally but visualizations fail (this is fixed in #589).
=> Change approach to listing supported MCDA methods

src/analysis/sensitivity.jl
Available GC threads get exhausted for large sample sizes (>= 8192) when using mutable static vectors as cache.
I believe because under the hood the vectors are represented as tuples, and modifying contents triggers GC to run.
Switching to plain vectors resolves the issue and does not drastically hurt performance.
=> Support RSA with large sample sizes

src/Domain.jl, src/decision/location_selection.jl, src/ecosystem/connectivity.jl
Changes in MCDAvars mean leftover space in $m^2$ is now an input to MCDAvars instead of cover (introduced in #547). Cover was still being used as an input in the `MCDA_vars` usage in `rank_locations`, causing incorrect outputs in testing.
=> Fix bug where cover instead of leftover space was being used in stand alone site selection

src/ecosystem/Ecosystem.jl, src/io/sampling.jl
Move `_check_discrete()` and `map_to_discrete()` methods into `sampling.jl` from `Ecosystem.jl` to maintain conceptual consistency.
This PR depends on #631 which should be merged first if possible. Currently this PR targets `[fix-set-factor-bounds](https://github.com/open-AIMS/ADRIA.jl/tree/fix-set-factor-bounds)` but could be rebased if/as necessary.
=> Consolidate methods that transform factor values into `sampling.jl`

src/decision/dMCDA.jl, src/decision/mcda_methods.jl
This PR fixes a couple of bugs found in mcda methods during testing.
VIKOR method has been returning NaNs in the case where some weights are zero. This is due to the formulation of the Q score, which requires division by (column max - column min). This has been fixed by adding a line in the VIKOR method which removes any zero columns.
ROV method was found to be incorrectly reversing site ranks. An example of this is :
```julia
results.scores =
0.6371641507442964
0.6941436816327351
0.877935879420678
1.0066403672998092
1.033670846678704
1.5902842580982375
1.7501562536882735
0.5729368306847074
0.4478149807103405
0.4484346568894094
results.bestIndex =2
```
In this case, site 2 is neither the highest nor lowest score. This suggests either a bug in JMcDM, or that the method searches for …
=> Fix mcda method bugs 

src/decision/mcda_methods.jl, src/io/ResultSet.jl
A bug was introduced in the previous fix #629, as it does not handle cases where only a single location is viable, resulting in an empty decision matrix.
=> Address MCDA error for single locations

ext/AvizExt/AvizExt.jl, src/ADRIA.jl
Julia v1.10 has moved to an asynchronous/parallel precompilation process.
The GLMakie-based prototype UI currently included with ADRIA (invoked by calling `ADRIA.explore(rs)`) makes use of a Timer to limit the number of UI updates that can occur.
The new precompilation process seems to wait for the timer to finish or otherwise enters into some kind of wait state.
The changes in this PR:
1. Adjusts use of Timer to only become active as users interact with the UI, avoiding any active state during precompilation, and 
2. Disables the precompilation workload to avoid similar issues.
Regarding point 2, some of the errors seem to stem from dependencies rather than ADRIA itself so I've opted to simply disable the precompilation workload for now.
This PR should address and close #645.
=> Changes to make ADRIA precompilable under Julia v1.10

ext/AvizExt/AvizExt.jl, ext/AvizExt/layout.jl, ext/AvizExt/viz/spatial.jl, test/runtests.jl
Addresses errors due to use of now fully deprecated keywords for Makie (v0.20.4) / GeoMakie (v0.6.0).
GeoMakie has updated (but the docs have not). The previous approach to setting lon/lat limits and associated tick labels does not work anymore.
The figure looks cleaner perhaps, but it would still be nice to see where we're looking at. In any case, I've opted to leave these off by default for later investigation.
=> Update use of Makie/GeoMakie to address deprecation errors

ext/AvizExt/viz/scenarios.jl
Specify a default figure size to make it look nicer "out of the box".
=> Add a default size for scenario plots

src/ExtInterface/ReefMod/Domain.jl, src/ecosystem/Ecosystem.jl, src/ecosystem/connectivity.jl, src/ecosystem/corals/growth.jl, src/io/inputs.jl, src/io/result_io.jl, src/scenario.jl
Previous implementation was erroneously looping over all size classes for all functional groups, skipping only size classes 1 and 2 for the first functional group.
We now loop over all non-juvenile size classes for all functional groups as expected.
=> Fix bleaching mortality 

src/ExtInterface/ReefMod/Domain.jl
ReefModDomain type loads up DHW datasets by pattern matching the relevant RCP code ("26", "45", "85", etc).
The RME dataset includes a file that holds historic data from 1985, which inadvertently gets included in the file list.
This change avoids this situation by also requiring the identified files have an "SSP" prefix.
=> Only load up relevant RME SSP datasets

docs/src/usage/scenario_generation.md, src/io/sampling.jl, src/scenario.jl, test/Ecosystem.jl, test/runtests.jl, test/sampling.jl
Clean up model run process for simplicity and conceptual validity.
Removes deprecated interface functions as well.
Addresses issue with NaN poisoning. 
RME datasets where empty wave datasets inadvertently resolves to NaN (due to max normalization with 0 values).
This has a flow-on effect to DHWs, resulting in DHW data being NaNs as well.
I've also corrected `set_factor_bounds!()` as it implies an in-place update will occur but this is only true if the function is called directly from the "main"/top-level module. If called from within another function, the updated `Domain` is not returned.
=> Clean up scenario running methods

src/ExtInterface/ADRIA/Domain.jl, src/ExtInterface/ReefMod/Domain.jl, src/decision/dMCDA.jl, src/decision/location_selection.jl, src/ecosystem/connectivity.jl, src/ecosystem/corals/growth.jl, src/io/result_io.jl, src/scenario.jl, test/connectivity.jl, test/data_loading.jl
Connectivity matrices do not need to sum to 1, as it indicates the proportion of larvae that reach a sink location.
Transition probability matrices are now conceptualised as indicating the contribution of larvae from a source location to a sink location (i.e., the columns should sum to 1).
The changes in this PR clarifies the use of these terms and data.
=> Clean up use of TP matrices to align with conceptualisation of connectivity

src/ecosystem/Ecosystem.jl
As in title.
Currently causes an error to be raised as `m` never gets defined.
The "real" fix is to find out under what conditions lb becomes > ub (which will be a different PR).
=> Return 0 in cases where lb > ub

ext/AvizExt/viz/sensitivity.jl, ext/AvizExt/viz/viz.jl, src/analysis/sensitivity.jl
Fixes readjustment of number of slices bug in RSA (partially addresses #615) and changes output of RSA to `YAXArrays.Dataset` type.
=> Fix readjustment of number of slices bug in RSA

src/ecosystem/Ecosystem.jl, test/Ecosystem.jl
Added truncated normal changes to speedup calculation of truncated normal mean and cdf.
The test cases are more relaxed to account for the loss of accuracy resulting from the approximation. 
The if statement warning about accuracy is now more specific in what it detects requiring both truncated bounds be on the same side of the mean as this was the source of cancellation errors. During the test runs done bellow, the warning was not encoutnered
The following plot is **without changes** contained in this pull request.
The following plot is **with changes** contained in this pull request.
closes #572
=> Truncated normal changes

src/factors/Factors.jl, src/interventions/Interventions.jl, src/io/sampling.jl, test/sampling.jl
Recently, when trying to do some scenario runs to sweep through larger factor bounds, I ran into an issue where certain distributions cannot be set.
This PR allows the user to set whatever bounds they wish, so long as they specify the necessary distribution parameters.
Factor types and their expected parameters are:
- `DiscreteOrderedUniformDist` : `(min, max, step)`, 
- `TriangularDist` : `(min, max, peak)`
```julia
dom = ADRIA.load_domain(some_domain)
dom = ADRIA.set_factor_bounds(
dom,
N_seed_TA=(Int(1e6), Int(5e10), Int(1e6)),
N_seed_CA=(Int(1e6), Int(5e10), Int(1e6)),
N_seed_SM=(Int(1e6), Int(5e10), Int(1e6)),
a_adapt=(0.0, 30.0, 0.0),
seed_freq=(1, 5)
)
```
=> Allow user to set whatever bounds they wish

src/analysis/sensitivity.jl, test/runtests.jl
Closes #692
Note: Tests for `outcome_map()` have been commented out as this function now refers to a function which no longer exists. This will be resolved shortly when addressing #615
=> Remove `factors` input from `rsa()` and use scenario dataframe column names instead

deps/build.jl
Removes installation of MKL (the Intel-specific math library) on computers with Intel CPU.
The purpose was to improve runtimes (small but noticeable) due to the large number of matrix operations.
However, it has been noted that deploying to AWS via Docker containers:
1. the end target system may not be an Intel based CPU at all
2. Docker build current fails when MKL is included.
Given the long-term plan is to leverage GPUs for matrix operations, I've decided it is best to remove MKL now.
=> Remove MKL from build process

src/analysis/sensitivity.jl
This pull request would override changes on the (unmerged) branch [yax-sensitivity-analysis](https://github.com/open-AIMS/ADRIA.jl/tree/yax-sensitivity-analysis). The older branch seemed only to find and replace `NamedDimsArray` and was most likely unfinished.
This branch does not migrate `outcome_maps` as this function is migrated in #702. 
Part of #695
=> Yax sensitivity

src/ADRIA.jl, src/analysis/sensitivity.jl, src/decision/Criteria/DecisionPreferences.jl, src/decision/Criteria/FogCriteria.jl, src/decision/Criteria/SeedCriteria.jl, src/decision/dMCDA.jl, src/decision/location_selection.jl, src/io/sampling.jl, src/scenario.jl, test/sampling.jl, test/site_selection.jl
Changes to allow standalone use of MCDA.
This was the original usage for standalone assessment:
```julia
using ADRIA
dom = ADRIA.load_domain("path to domain", "45")
scens = ADRIA.sample_site_selection(dom, 8)
area_to_seed = 962.11
sum_cover = repeat(sum(dom.init_coral_cover; dims=1), size(scens, 1))
ranks = ADRIA.decision.rank_locations(dom, scens, sum_cover, area_to_seed)
sel_score = ADRIA.decision.selection_score(ranks[intervention=1])
scens = ADRIA.sample(dom, 8)
rs = ADRIA.run_scenarios(dom, scens, "45")
sel_score = selection_score(rs.ranks[intervention=1])
```
Note the user is expected to determine the area to be seeded and manually create initial cover data.
Note also the use of indices to specify dimensions
This is the new usage:
```julia
using ADRIA
dom = ADRIA.load_domain("path …
```
=> Update support for standalone MCDA use

src/scenario.jl
Workaround added to resolve #416 is now no longer needed as the memory leak has been resolved upstream in Julia v1.10.
The issue was likely caused by something to do with the (auto-)garbage collection process.
See other details noted in #405 .
Might require bumping the minimum supported Julia version to v1.10
=> Remove GC workaround

src/decision/dMCDA.jl, test/io/inputs.jl, test/mcda.jl, test/runtests.jl, test/site_selection.jl
A simple assessment is conducted to identify MCDA methods (provided by JMcDM.jl) that are suitable for use with ADRIA.
The details of the assessment are documented in `test/mcda.jl`.
The assessment is included as a test to indicate if/when JMcDM.jl methods change or are updated.
Five methods are identified, which are (in order):
- CoCoSo
- MAIRCA
- Moora
- PIV
- VIKOR
The script below is applies a modified version of the bootstrapped assessment discussed in https://github.com/open-AIMS/ADRIA.jl/issues/452#issuecomment-1942888428
The assessment indicates PIV is the most appropriate (based on this somewhat limited analyses of 256 samples per guided "type").
This is in contrast to the assessment done by @Rosejoycrocker in https://github.com/open-AIMS/ADRIA.jl/pull/702#issuecomment-1993564379 …
=> Validating MCDA methods and initial clean/update of tests

src/interventions/Interventions.jl, src/io/ResultSet.jl, src/io/result_io.jl, src/scenario.jl
Instead of using numbers for the interventions labels, which makes it difficult to work with the ranks later on, now they are being saved as symbols.
=> Save right intervention label at ResultSet ranks YAXArray

ext/AvizExt/viz/clustering.jl, ext/AvizExt/viz/spatial.jl
Previous implementation only supported YAXArrays, so if you could not easily plot an arbitrary dataset
```julia
some_values = [...]
ADRIA.viz.map(dom, some_values )
```
This PR expands the supported datatypes to include `AbstractVector{<:Real}`.
=> Support more vector types for maps

src/ExtInterface/ADRIA/Domain.jl, src/ExtInterface/ReefMod/RMEDomain.jl, src/ExtInterface/ReefMod/ReefModDomain.jl, src/decision/location_selection.jl, src/ecosystem/connectivity.jl, src/scenario.jl
This PR:
- Separates out determination of the strongest source locations
- Allows flexible use of alternate centrality measures in determining centrality
- Removes unused connectivity data from Domain types, making them more memory efficient
Previous implementation of the strongest source location violated the Single Responsibility Principle, as it was lumped in with all other connectivity-related calculations. In addition, it was unused but was being recalculated every decision point. As it was naively iterating through all nodes in the graph (rather than just target nodes of interest), it would take upwards of 10 seconds per decision point.
In the worst case for a large network (such as one representing the entire GBR), this would explode run times from ~2 hours to ~12 hours for a small …
=> Clean up connectivity and centrality methods

ext/AvizExt/viz/spatial.jl, src/viz/viz.jl
Add connectivity visualistion method.
```julia
dom = ADRIA.load_domain("<Path to Domain>")
in_conn, out_conn, network = ADRIA.connectivity_strength(dom; out_method=eigenvector_centrality)
ADRIA.viz.connectivity(
dom,
network,
out_conn;
opts=opts,
fig_opts=fig_opts,
axis_opts=axis_opts
)
```
Providing reasonable defaults for the graph visualisation is difficult because of the size of the graph and the variance from south to north. However, the interactivity somewhat remedies this. Feel free to provide suggestions.
=> Connectivity viz

test_performance/Manifest.toml, test_performance/growth_cuda.jl, test_performance/settler_cover_perf.jl
See changes.
I've changed the benchmark approach to simulate 75 time steps to better reflect use case (and align with the mock example shown previously).
Timings:
~10.9x faster compared to CPU but orders of magnitude slower than the mock example in #739.
Note the number of allocations explode when using the GPU approach. There's some memory allocations that could be avoided by either making a GPU-specific `recruitment_rate()` or pre-allocating arrays as necessary.
Note: In the code I comment that "`recruitment_rate()` takes < 1ms" but I'm not sure about that any more. Suspect there are additional memory allocations occurring.
Incidentally, in `recruitment_rate()` this line (`growth.jl:658`):
https://github.com/open-AIMS/ADRIA.jl/blob/aeeb749b9c1ea928504de9837af90e0331e59dde/src/ecosystem/c …
=> Working example of CUDA-fied `settler_cover()`

src/ecosystem/connectivity.jl
I should have found this when reviewing pull request #737. The connectivity strength was always using defaults instead of provided centrality measures. 
It also appears that the default connectivity visualisation is quite poor for small reefs.
```julia
in_conn, out_conn, network = ADRIA.connectivity_strength(dom.conn, out_method=eigenvector_centrality)
ADRIA.viz.connectivity(dom, network, out_conn)
```
closes #749.
=> use provided centrality measures instead of defaults

ext/AvizExt/AvizExt.jl, ext/AvizExt/viz/spatial.jl
```julia
using ADRIA
using GeoMakie, GraphMakie, GeoMakie
moore_dom = ADRIA.load_domain("<path to cluster-scale domain>")
gbr_dom = ADRIA.load_domain(RMEDomain, "<path to RME dataset>", "45")
ADRIA.viz.map(moore_dom)  # See figure 1
ADRIA.viz.map(gbr_dom)  # See figure 2
```
Figure 1:
Figure 2:
I've yet to work out why the gridlines (with lat/longs) disappear for the smaller spatial scale, and why there is a relatively large space between the map and the colorbar.
Any thoughts @DanTanAtAims ?
FYI I've made the figures with the following Domain versions:
`Moore_2024-02-05b_v060_rc1` and `rme_ml_2024_01_08`
=> Improved support for spatial maps

src/ecosystem/corals/Corals.jl, src/io/ResultSet.jl, src/io/result_io.jl, src/metrics/metrics.jl, src/scenario.jl
Should allow complete scenario runs and analysis afterwards. 
I moved the planar_area array into a function call so that all/nearly all coral parameters are in one place.
=> remove hardcoded coral spec from metrics and data store

docs/make.jl, docs/src/usage/results.md, ext/AvizExt/viz/scenarios.jl, src/ADRIA.jl, src/io/ResultSet.jl, src/io/rme_result_io.jl
Results from ReefModEngine.jl can be loaded with the `load_results` function. There are two options depending on the location of the results and accompanying data files. The datafiles in the RME directory can be used as the data directory.
```julia
rs = ADRIA.load_results(RMEResultSet, "<path to data dir>", "<path to results dir>")
```
Expected data directory structure.
```bash
data_dir
│
├───con_bin
│       CONNECT_ACRO_2010_11.bin
│       CONNECT_ACRO_2011_12.bin
│       CONNECT_ACRO_2012_13.bin
│       CONNECT_ACRO_2014_15.bin
│       CONNECT_ACRO_2015_16.bin
│       CONNECT_ACRO_2016_17.bin
│
├───id
│       id_list_2023_03_30.csv
│
└───region
reefmod_gbr.gpkg
```
The results data directory should contain a `results.nc` NetCDF file and `scenarios.csv`. If
the path to the results …
=> RME Result Interface

src/scenario.jl
This is the same fix added in #761.
Cyclone mortality was only being applied to the last function group of corals in the middle size classes.
=> add range to for loop

src/ecosystem/corals/growth.jl, src/interventions/seeding.jl, src/scenario.jl
The commits reshape `C_cover` from `time x group_size x locs` to `time x group x size x locs`.
This involves providing duplicate implementations of processes that accept multidimensional inputs. The new implementations are for `proportional_adjustment`, `fecundity_scope`, `settler_DHW_tolerance`, `seed_corals`, `bleaching_mortality`, and `cyclone_mortality`. These changes are limited to functions called within `run_model`.
There is probably no rush to merge, to make the review easier compare the new function implementations with the non-multidimensional equivalents
=> Multidimensional cover

docs/src/usage/domain.md, docs/src/usage/getting_started.md, src/ExtInterface/ADRIA/Domain.jl, src/ExtInterface/ReefMod/RMEDomain.jl, src/ExtInterface/ReefMod/ReefModDomain.jl
Clarify that path is to the directory, not the datapackage.json file.
Note: could make ADRIA support pointing to either, but just updating the docs for now.
=> improve load_domain docs

src/interventions/Interventions.jl
Previously the assisted adaptation factor - indicating the level of enhancement/efficacy in terms of increased DHW tolerance - was defined as a Triangular Distribution.
I am changing this to a DiscreteOrderedUniform distribution to reflect that no one knows what the likely level of enhancement is.
=> Change assisted adaptation to a Discrete Uniform value

ext/AvizExt/viz/environment/dhw.jl
Addresses issue where data is misplaced in the figure
With fix:
=> Use underlying data instead of YAXArray type

ext/AvizExt/viz/spatial.jl
As in title.
Simple one line fix to docstring.
=> Fix mismatched function name in docstring

src/scenario.jl
Add growth constraints based on available area. 
The initial implementation in the main branch uses `actual_growth = growth * log(1 + leftover space)`. 
This implementation uses `actual_growth = growth * log(2, 1 + leftover space)`. Using log base 2 so that when leftover space is 100% the log is 1 and growth is unconstrained.
This assumes the growth rates being used are unconstrained growth rates which probably isn't the case and depends on available space when the measurement took place.
=> constrain growth by available area

ext/AvizExt/viz/clustering.jl, ext/AvizExt/viz/location_selection.jl, ext/AvizExt/viz/rule_extraction.jl, ext/AvizExt/viz/scenarios.jl, ext/AvizExt/viz/sensitivity.jl, ext/AvizExt/viz/spatial.jl, ext/AvizExt/viz/taxa_dynamics.jl, ext/AvizExt/viz/viz.jl
The update to use `Dict{Symbol,<:Any}` in `ADRIA.viz.map` for optional arguments caused type mismatches in visualisations that were using mapping. Specifically, spatial visualization of clustering results.
This pull requests fixes this mismatch and allows tests to be run without erroring again.
=> Fix visualization type error

ext/AvizExt/viz/clustering.jl, ext/AvizExt/viz/scenarios.jl
As in title. Default order is "counterfactual", "unguided", "guided".
> NOTE: When plotting clusters, the legend is always in the same order, but the plot order might change depending on `sort_by`
Below are some plots of scenarios and clusters, sorted by default, variance and size:
| `sort_by` | Scenarios | Cluster |
| -------- | --------- | ------- |
| `:default` | ![image](https://github.com/open-AIMS/ADRIA.jl/assets/8040719/76e1c441-cfe9-4306-ac55-de2e108a9e49) | ![image](https://github.com/open-AIMS/ADRIA.jl/assets/8040719/22faffe3-aa72-48d1-bd58-57ce3445d774) |
| `:default` | ![image](https://github.com/open-AIMS/ADRIA.jl/assets/8040719/decdbc86-cb31-4c5c-842d-91cef6984d36) | ![image](https://github.com/open-AIMS/ADRIA.jl/assets/8040719/f69fafac-eca0-48f3-bf1f-807f17acde6e) |
| …
=> Add default option to _sort_keys

ext/AvizExt/theme.jl, ext/AvizExt/viz/scenarios.jl, src/analysis/clustering.jl, src/analysis/rule_extraction.jl
- Add option to pass `lambda` param when running SIRUS
- Add option to choose distinct clustering algorithm with `cluster_series` and `cluster_scenarios`
- Add option to use distinct distance measurement with `cluster_series` and `cluster_scenarios`
- Standardize `target` and `non-target` plot colors (use the same colors as in SIRUS scatter plot)`
=> Assortment of improvements to SIRUS and Time Series Clustering 

ext/AvizExt/viz/spatial.jl
As in title.
Closes #792
```julia
dom = ADRIA.load_domain("<path to domain>")
dom2 = ADRIA.switch_RCPs!(dom, "45")
ADRIA.viz.map(
dom2,
vec(mean(dhw_scens[timesteps=At(20)], dims=2));
opts=Dict(:color_map => :lighttest),
axis_opts=Dict(:title => "Mean DHW 2045")
)
```
Note this is a temporary fix on top of a temporary implementation.
Further work to utilize/leverage GeoMakie/GeoDataFrames functionality much more is needed.
=> Coerce to MultiPolygon instead of Polygon

ext/AvizExt/viz/scenarios.jl, test/runtests.jl
Minor fix to resolve failing test related to scenario clustering/confidence intervals.
Tests still fail due to unrelated issues, but this is a step towards resolving them.
=> Address tests failing due to type mismatch (scenario confint)

ext/AvizExt/viz/scenarios.jl, test/clustering.jl
- Clustering test was broken because the test data we use is a 3x3 matrix and the new clustering method requires the maximum number of clusters to be the size of this matrix. 
- In some cases, scenarios plot was raising an error when we tried to call `series!` passing an YAXArray of data as input. 
This PR fix those two issues.
=> Fix broken tests

src/ExtInterface/ReefMod/RMEDomain.jl
Unfortunately, I appeared to have incorrectly loaded RMEDomain initial cover when migrating to use CoralBlox. @Zapiano @ConnectedSystems 
This wouldn't impact calibration runs as initial cover is overwritten.
The first taxa has very small initial cover which is actually the initial cover values for the small size classes and the last taxa has very large cover values.
2 counterfactuals
=> fix permutation of initial cover dimensions

.git-blame-ignore-revs, docs/Manifest.toml, docs/src/development/development_setup.md
The doc builder failed:
https://github.com/open-AIMS/ADRIA.jl/actions/runs/10361183116/job/28681006319
I've regenerated the `docs` Manifest, which should fix this.
Also, added `.git-blame-ignore-revs`, which ignores the "re-format entire project" commit from #790
Documented how to activate `.git-blame-ignore-revs`
=> Fix docs builder, add .git-blame-ignore-revs and document

src/scenario.jl
Resolves #826
Reshape retains order of size classes then species. Seems some repetitiveness though in logged values, maybe it can be further aggregated?
=> Add reshape to fix dimension mismatch when logging dhw tolerances

.github/workflows/documentation.yml
Bump the Julia version for the documentation build action.
This should fix the Pkg error.
`1.10` matches `1.10.*`
https://github.com/julia-actions/setup-julia?tab=readme-ov-file#julia-versions
=> updates docs github action to use Julia 1.10.*

.gitignore, Manifest.toml
Since Julia only needs the Project.toml file to recreate a Manifest.toml, there is a discussion if it is a good practice to add it to gitignore. We decided to remove the Manifest.toml from gitignore to increase reproducibility. 
A discussion about that topic can be found here: https://discourse.julialang.org/t/putting-manifest-toml-in-git/94144/7
=> Remove Manifest from gitignore

docs/Manifest.toml, docs/src/architecture/domain_and_resultsets.md, docs/src/usage/analysis.md
This fixes the errors that appeared after upgrading `Documenter` from `0.27.25` to `1.5.0`
Example Error:
```
┌ Error: invalid local link/image: file does not exist in src\usage\analysis.md
│   link =
│    @ast MarkdownAST.Image("../assets/imgs/analysis/single_rank_plot.png \"title text breaks\"", "") do
│      MarkdownAST.Text("Rank frequency plots for single rank")
│    end
```
Also, ran Pkg `update`, so now we're on `1.6.0`
title text doesn't work in current docs, and `raw=true` seems to have no effect for our largest png on GitHub. So I don't think we're losing anything with the changes in this PR.
These errors appeared because Documenter 1.0 switched to strict mode.
https://github.com/JuliaDocs/Documenter.jl/blob/v1.6.0/CHANGELOG.md#version-v100---2023-09-15
Also, Documenter does not …
=> Fix docs errors

src/scenario.jl
Marking this as draft because changes would need to be made to growth constraints to consider recruits.
`CoralBlox` accepts recruitment as `area` not `relative area`. 
16 `RMEDomain` countfactuals
=> convert recruitment from relative area to area before use

docs/src/usage/results.md, ext/AvizExt/viz/scenarios.jl, src/ecosystem/corals/Corals.jl, src/io/cscape_result_io.jl
Reduced ResultSet load times from \~2:10 mins to \~27 seconds for a 20 scenario dataset.
Note, improvements will be more noticeable if more each C~Scape dataset holds more than a single scenario.
Achieved by:
1. A "smarter" indexing strategy used to read C~Scape results into a common data structure
Precalculates the indices for the scenarios in each dataset to avoid `if` branching in the loop
2. avoiding loading/calculating data where results are all zeros, 
3. reading in data into memory prior to any calculations
I've also organized the function definitions so that methods with the same names are together in the file, as per style guide.
I also applied the formatter so it passes the format check we now have in place.
=> Cscape interface improvements

docs/src/development/docker.md
Minor fix to remove stale relative links from markdown docs.
=> fix: stale links in docker docs

docs/src/usage/analysis.md, ext/AvizExt/viz/sensitivity.jl, src/analysis/sensitivity.jl, src/io/datacubes.jl, test/runtests.jl
Fixes bug where the number of bins was being set by the maximum number of categories where a categorical variable was used. Also moves similar code used in `sensitivity.rsa` into functions to be used by both methods.
Closes #615
=> Fix error in bin size for `sensitivity.outcome_map`

src/analysis/sensitivity.jl, test/runtests.jl
Recent PR #702 included a type that was overly constrained which causes tests to fail.
Resolved by allowing any AbstractVector holding values <: Real.
=> Overly constrained argument types causing tests to fail

src/ExtInterface/ReefMod/ReefModDomain.jl
Corrects the domain to only load 5 functional groups instead of 6. 
closes #825
=> fix reefmod domain load initial cover

src/io/cscape_result_io.jl
1. Correct the calculation of maximum available coral cover in result loading
2. Remove the manual site data correction (new dpkg available on teams in ADRIA result sets, `cscape_dpkg_2024_09_16.zip`)
3. Use `loc` instead of `site` to maintain compatability with existing `ResultSet`
closes #849
=> Update interface to use correct gpkg

src/io/cscape_result_io.jl
Corrections to relative cover calculations.
1. Divide by area of each location (summing intervened and non-intervened area)
2. Divide by 100 to convert percentage to proportion.
=> correct calculation of relative cover

src/io/cscape_result_io.jl
Use the [NetCDF.jl](https://github.com/JuliaGeo/NetCDF.jl) api instead of [YAXArrays](https://github.com/JuliaDataCubes/YAXArrays.jl) to load netcdf data.
Loading 22 files now takes around 1 second.
Loading a variable from 22 files takes around 1 second as well.
It would be good to see if this scales well to 2000 files.
=> Speed up CScape Result Interface

src/io/cscape_result_io.jl
Uses `ArgumentError` and `throws` the error.
close #856
=> throw more informative error message

src/metrics/site_level.jl
The previous approach, using JuliannedArrays.Slices, is taking too much to run for some unknown reason. Using `mapslices` seems to fix the problem.
closes #788
=> Improve summarize performance by using mapslices

src/ExtInterface/ReefMod/ReefModDomain.jl
The mortality for cyclones appeared to be higher for branching corals deeper then 5m than branching corals shallower then 5m deep.
=> Cyclone mortalities assigned to wrong group

ext/AvizExt/outcome_metadata.jl, ext/AvizExt/viz/clustering.jl, ext/AvizExt/viz/rule_extraction.jl, ext/AvizExt/viz/scenarios.jl, ext/AvizExt/viz/spatial.jl, ext/AvizExt/viz/taxa_dynamics.jl, ext/AvizExt/viz/viz.jl, src/metrics/metadata.jl, src/metrics/metrics.jl, src/metrics/reef_indices.jl, src/metrics/scenario.jl, src/metrics/spatial.jl, src/metrics/utils.jl, test/metrics/test_metrics_helper.jl, test/runtests.jl, test/viz/taxa_dynamics.jl
Closes #453 
Use metrics metadata to automatically generate title and labels for viz functions.
1. Not all viz functions were updated yet.
2. Maybe not in this PR, I need to display relative metrics as percentage. The reason why I don't want to do that in this PR is because is not only a label change. 
3. In order to update sensitivity analysis related viz functions, I'll need to update some sensitivity analysis functions too because they return an array without metadata. 
```
s_tac = ADRIA.metrics.scenario_total_cover(rs)
fig_s_tac = ADRIA.viz.scenarios(rs, s_tac)
```
```
s_rc = ADRIA.metrics.scenario_relative_cover(rs)
fig_s_rc = ADRIA.viz.scenarios(rs, s_rc)
```
```
tac = ADRIA.metrics.total_absolute_cover(rs)
loc_tac = ADRIA.metrics.per_loc(median, tac)
tsc_map_fig = ADRIA.viz.map(rs, …
```
=> Viz metadata

ext/AvizExt/viz/location_selection.jl, ext/AvizExt/viz/spatial.jl
See initial investigative notes here: https://github.com/open-AIMS/ADRIA.jl/issues/890#issuecomment-2434642334
I'm still unsure of the exact cause as I can get tests to pass when `infiltrate`d by first calling `reset_limits!(current_axis())` to invoke the error, and then `@continue`ing on.
My first suspicion was on the custom [legend parameter creation](https://github.com/open-AIMS/ADRIA.jl/blob/578999fe836d759ac5c1aac1098cbf5d1c4425a9/ext/AvizExt/viz/clustering.jl#L185-L205), but it seems to be fine outside the test context.
Removing the two offending lines of code allows tests to pass.
The resulting figure seemed as expected with the exception of gridlines being out of alignment.
So I have set gridlines to false by default for maps for now.
Tests pass locally for me.
Closes #890
=> Fix StackOverflow error when plotting maps

src/analysis/rule_extraction.jl, test/analysis.jl
Add optional kwarg to `cluster_rules` to allow for removing duplicate rules. The criteria to choose
which rule to keep is based on the rule consequence probability: the one with the highest probability is kept. If more than one rule has the same highest probability, the first one is chosen.
Example of two plots one with and one without duplicated rules (the duplicated rule is `Assisted Adaptation & Selection Frequency (Seed)` (3rd row, 2nd and 3rd cols on the second figure):
=> Remove duplicate rules

docs/src/usage/analysis.md, src/analysis/rule_extraction.jl, test/analysis.jl
Note: This branch is based on #863 's branch. Closes #672 .
---
Updates `ADRIA.analysis.cluster_rules` so we can check for constant factors (and ignore them) before trying to extract rules. The parameters you need to pass to `cluster_rules` have changed - with that is one line less of code now.
The documentation still needs to be updated - once this is done, I'll mark this as ready to review.
As an example, let's fix all `SeedCriteriaWeights` and only a few of the `FogCriteriaWeights` factors, run the model, cluster and target some cluster:
```
dom = ADRIA.load_domain("...")
ADRIA.fix_factor!(
dom;
seed_out_connectivity=0.9,
seed_heat_stress=0.8,
seed_depth=0.7,
seed_coral_cover=0.5,
seed_in_connectivity=0.4,
seed_wave_stress=0.0,
fog_coral_cover=0.5,
fog_depth=0.7
)
num_scens = 2^8
scens …
```
=> Fix rule extraction to handle constant factors

src/Domain.jl, src/io/sampling.jl
Adding the following:
```julia
coral_params = ADRIA.component_params(dom, ADRIA.Coral)
ADRIA.fix_factor!(dom, [:N_seed_TA, :N_seed_CA])
```
The addition extends already existing method names and simplifies their use.
pinging @Zapiano  @DanTanAtAims for awareness.
Skipping the usual review process in the interest of time given the low risk.
=> Add additional convenience functions and update docstrings

src/interventions/seeding.jl, src/scenario.jl
Code flow in `run_model()` is very convoluted so I extracted and refactored the key process for coral deployments so what is happening in the main loop is more obvious.
`seed_corals!()` is now consolidated into the `run_model()` method, allowing some defunct code to be cleaned up.
=> Remove defunct method `seed_corals!`

ext/AvizExt/viz/environment/cyclones.jl, ext/AvizExt/viz/environment/dhw.jl, src/io/inputs.jl
Trying to load RME data and found this issue has cropped up again.
Before:
After:
Before merging I will check the latest site-level Domains work as expected.
=> Fix DHW scenario viz again

src/interventions/seeding.jl, src/scenario.jl, test/seeding.jl
**Please note: This PR requires #909 to be merged in first.**
Previously we were logging the proportional area increase for each deployment location.
For analyses, I think it makes more sense to assess the number of coral deployed at each location instead, particularly for bump hunting and feature analysis.
@DanTanAtAims sorry to overload you - I requested a review from @Zapiano initially, but realised because this PR relies on #909 , whoever reviews that one would have better context on the changes here.
Please check my math used to derive deployed number of corals with a fine-tooth comb.
=> Switch to logging number of coral deployed

Manifest-v1.11.toml, docs/Manifest.toml, docs/Project.toml
The workflow of building the documentation was failing. Following commit 323d65f, this commit add and pin DiskArrays to 0.4.9 in the docs Manifest and in Julia v1.11 Manifest. It also updates the docs manifest.
=> Pin DiskArrays to 0.4.9 in docs Manifest and v1.11 Manifest

test/metrics/spatial.jl, test/viz/spatial.jl
Running metrics/spatial and viz/spatial tests raised this error: `ERROR: LoadError: UndefVarError: 'cf_difference_loc' not defined`. This error was caused because commit 46fd368 renamed the function cf_difference_loc to ensemble_loc_difference but it was still imported in the test function. The function was not being used.
This commit removes the import of cf_difference_loc function.
=> Fix tests of viz/spatial and metrics/spatial

src/scenario.jl
Reshape and consecutive multiplication was triggering runtime dispatch.
Using the view of the matrix directly avoids triggering a runtime dispatch.
Collapsing the single dimension resulted in a [n_group * n_loc] matrix anyway.
This change results in a ~10% speed up, with a 512 scenario run going from ~8mins to just over 7mins for a small cluster.
GBR-scale runs may result in better runtime performance.
I confirm the change produces identical results:
=> Avoid reshape for performance

src/Domain.jl, src/analysis/intervention.jl, src/decision/dMCDA.jl, src/factors/Factors.jl, src/interventions/Interventions.jl, src/io/sampling.jl, test/sampling.jl
Tentative Initial implementation of categorical variables in ADRIA.
```julia-repl
julia> dom = ADRIA.load_domain("<path to domain>")
julia> ADRIA.set_factor_bounds(dom, :guided, ("counterfactual", "Vikor", "Piv"))
julia> scens = ADRIA.sample(dom, <n_scenarios>)
32×317 DataFrame
Row │ dhw_scenario  wave_scenario  cyclone_mortality_scenario  guided   N_seed_TA   N_seed_CA   N_seed_SM   min_iv_locations  cluster_max_member  fogging     SRM       a_adapt  seed_years  shade_years  fog_years  plan_horizon  see ⋯
│ Float64       Float64        Float64                     Float64  Float64     Float64     Float64     Float64           Float64             Float64     Float64   Float64  Float64     Float64      Float64    Float64       Flo ⋯ …
```
=> Custom categorical distribution

src/io/result_io.jl
As in title.
There was a missing underscore in generated directory name.
=> Correct RCP identifier in result directory

ext/AvizExt/viz/taxa_dynamics.jl
The following tweaks were applied:
- Reduced large display of plot (1200x1200 to 1200x600)
- Adjust title text to be in title case
- Change position of legend to left hand side to avoid hiding other plot elements. This should be moved outside the plot but I don't have time to make the necessary adjustments.
One change I needed but couldn't work out was changing the scenario type name to title case ("counterfactual" -> "Counterfactual").
Please note there was some chatter about `viz.taxonomy` in another issue, I'm not sure if the changes there will impact this PR.
https://github.com/open-AIMS/ADRIA.jl/pull/896#issuecomment-2597022820
=> Minor tweaks to taxa visualization

.JuliaFormatter.toml, docs/src/development/development_setup.md
Add clearer docs on how to set up the Julia Formatter extension.
The Julia Formatter package is only relevant if running the formatting manually or in CI/CD
=> Update docs to configure Julia Formatter extension

docs/src/usage/analysis.md, src/ADRIA.jl, src/Domain.jl, src/decision/dMCDA.jl, src/decision/location_selection.jl, src/io/ResultSet.jl, src/metrics/metrics.jl, src/metrics/scenario.jl, src/scenario.jl, test/mcda.jl, test/run_scenarios.jl
Replaces remaining instances of `site_k_area()` with `loc_k_area()`.
Deprecates `site_k_area()` so any use gets auto-forwarded to `loc_k_area()` (with `@deprecated`, a new macro I discovered).
Closes #564
=> Replace and deprecate remaining use of `site_k_area`

src/ADRIA.jl, src/Domain.jl, src/scenario.jl
In the rare case where adding the recruits to a location cover should fill an entire reef, so that the relative cover would be equal to 1, sometimes there's a rounding error causing the actual relative cover to be 1 plus a very tiny number (one of the times I've checked it was close to 1e10-11). That causes a few issues and the fix is to set a threshold (right now it's set to 0.95 but that can be changed) so that:
- If that location's relative cover is already above the threshold, we set the recruits to zero.
- If that location's relative cover is below the threshold but when adding the recruits it goes above the threshold, we rescale the recruits so that this sum is equal to the threshold
- Otherwise we do nothing
And that seems to fix the problem. 
Note that:
1. To cause this bug in the …
=> Fix rounding problem, leading to coral overgrowth, when cover plus recruits fill an entire reef

src/analysis/clustering.jl
This is essentially the same as #940 but I've created a separate PR because the other branch was too behind the main and a rebase was creating a few unwanted commits for some reason.
The two main changes here are:
1. Since the distance matrix is symmetric, the inner loop limits were changing to avoid going through the same matrix elements more than once
2. `@floop` was replaces by `Threads.@threads`. Not sure why, but a simple banchmark using Chairmarks showed that it actually works (in the dfigure below, the first benchmark was done using `@loops` and the second using `Threads.@threads`):
Credits to @eco-ben who actually found this.
=> Speed up timeseries clustering
