src/analysis/sensitivity.jl

Add temporal sensitivity analyses based on the PAWN method

---

src/Domain.jl
src/ecosystem/Ecosystem.jl

Adds parameter name and description to model specification.
Aside from creating a nice overview table of parameters, their values, and ranges, it can be used to produce labels and tooltips for UIs.
Closes #230

Add parameter name and description to model specification

---

src/ecosystem/Ecosystem.jl
src/scenario.jl

Adjusts growth rates for size class 6 once at initialization as opposed to every simulation.
Closes #268

Adjust coral growth rate for size class 6

---

README.md
docs/src/index.md
docs/src/usage/domain.md

As in title. Remove last vestiges of "Input Set"
Closes #246

Remove references to Input Set

---

src/io/ResultSet.jl
src/io/result_io.jl

Replace use of abstract types with parametric/concrete types for the ResultSet definition

Parametric ResultSet

---

Aviz/src/plotting.jl
README.md
src/analysis/analysis.jl
src/analysis/sensitivity.jl

Rename `normalize` functions which applied normalization on a per-column basis to better reflect what they do.

Consolidate normalize

---

examples/site_selection.jl

- correct domain typo
- add to documentation
- makes sure sum cover dims matches criteria_df dims

Changes to address bug in site_selection example (addresses issue #285 )

---

src/ecosystem/Ecosystem.jl
src/sites/dMCDA.jl

- adds new integer parameter 'use_dist' which =1 when distance sorting is to be used and 0 when distance sorting is not to be used
- addresses issue #238

Add criteria parameter which indicates whether distance sorting is used.

---

examples/running_scenarios.jl
examples/sampling_scenarios.jl
src/Domain.jl
src/io/ResultSet.jl
src/main_app.jl
src/metrics/metrics.jl
src/scenario.jl

Standardizing code styles, and simplifying logic when running batches of scenarios

Miscellaneous cleanup

---

src/ecosystem/corals/spec.jl
src/io/result_io.jl
src/metrics/metrics.jl
src/metrics/scenario.jl
src/scenario.jl

Closes #292
Fixes for the juvenile density indicator and standardization of some function names.

Fix bug causing implausible juvenile indicator values

---

src/ecosystem/Ecosystem.jl
src/io/sampling.jl
test/sampling.jl

Fix error mapping continous samples to discrete values

---

src/analysis/analysis.jl
src/analysis/intervention.jl
src/analysis/pareto.jl
src/analysis/site_selection.jl
src/io/ResultSet.jl

- allows plotting of site selection frequency choropleth maps using `create_map!` to plot frequencies.
- can take output of `find_robust()` to plot site selection frequency of robust scenarios.

Adds function which calculates sites selection frequency for a set of provided samples

---

src/analysis/sensitivity.jl

Check for a single unique value rather than `all() == 0 `

Better check for constancy in RSA

---

Aviz/src/Aviz.jl
Aviz/src/analysis.jl

Minor changes and adjustments to match latest ADRIA API so that the UI loads correctly.

Update exploration tool to latest ADRIA API

---

src/ADRIA.jl
src/Domain.jl
src/ExtInterface/ReefMod/Domain.jl
src/ecosystem/Ecosystem.jl
src/sites/dMCDA.jl

Tentative implementation of an interface for ReefMod data, supporting selection of intervention deployment locations

Initial ReefMod interface and functionality

---

Aviz/src/Aviz.jl
src/ecosystem/Ecosystem.jl
src/sites/dMCDA.jl

Controls how many years worth of projected data are used to determine deployment locations.
In a sense, indicates level of confidence in our projections of DHW and waves. Increasing the value means we have greater confidence, reducing it means we are more confident in shorter-term projections.

Add planning horizon factor

---

src/scenario.jl
src/sites/dMCDA.jl

Pass in subset of sites to be considered when running ADRIA simulations

Fix error caused by mismatched locations

---

.gitignore
src/ADRIA.jl
src/Domain.jl
src/ExtInterface/ADRIA/Domain.jl

As in title.
Treat all models as interactable components via a defined external interface.

Split ADRIA-mod domain definition

---

src/ecosystem/const_params.jl

Add GBR zones by priority.
Cherry-picked commit from PR #330

Add GBR zones by priority

---

docs/make.jl
docs/src/usage/scenario_discovery.md

Add initial scenario discovery page to documentation

Scenario discovery docs

---

src/sites/dMCDA.jl
test/site_selection.jl

Closes #366
Adds test to check that rankings line up with site ordering in s_order.

Address ranking errors in mcda outputs

---

src/ecosystem/corals/growth.jl

Update docstrings for growth function

---

src/scenario.jl

Puts greater weight on environmental conditions closer to the decision point than far future conditions when determining deployment locations

Consider near-term conditions with greater weight than far-future conditions

---

docs/src/development/development_setup.md
docs/src/development/release_guide.md
test/seeding.jl

Updated release guide for clarity.

Update release guide

---

src/ecosystem/corals/growth.jl
test/growth.jl

Created during some earlier refactoring. Removing in favour of `recruitment_rate`

Remove duplicate function `recruitment`

---

src/scenario.jl

Update comment to reflect changes in #397

Update comment to reflect changes for wave condition usage

---

docs/src/usage/analysis.md
ext/AvizExt/viz/scenario.jl

Place density plot with histogram.
Things left to do:

Scenario viz change

---

src/ecosystem/corals/growth.jl

Update docstrings with missing detail

---

ext/AvizExt/theme.jl
ext/AvizExt/viz/clustering.jl
ext/AvizExt/viz/scenario.jl

Minor changes to allow scenario subsetting and correcting typos in docstrings

Small miscellaneous changes for scenario visualizations

---

ext/AvizExt/theme.jl
ext/AvizExt/viz/clustering.jl
ext/AvizExt/viz/scenario.jl
src/analysis/rule_extraction.jl

Implement necessary functions to use Julia implementation of SIRUS rule extraction algorithm (https://github.com/rikhuijzer/SIRUS.jl).
Closes #404.

Implement rule extracting function

---

src/io/sampling.jl

Fix error when running samples generated from `sample_site_selection()`

---

ext/AvizExt/AvizExt.jl
ext/AvizExt/viz/spatial.jl

As in title.
Includes minor fix to make locations appear properly for spatial visualizations

Update prototype exploration UI to work with recent changes

---

README.md

After the team agreed to follow Blue Style Guide, the Blue Style Guide badge is being added to the REAMDE file together with a paragraph informing that we are starting to move in this direction.

Add Blue Style Guide badge to README

---

ext/AvizExt/viz/rule_extraction.jl
ext/AvizExt/viz/sensitivity.jl
ext/AvizExt/viz/viz.jl
src/viz/viz.jl

This plot may be useful for bump hunting in the future. It is a first  way of visualizing the rules extracted using SIRUS algorithm.

Implement rule scatter plot function

---

ext/AvizExt/viz/viz.jl

Include rule_extraction.jl in viz.jl

---

src/analysis/sensitivity.jl

Update sensitivity module to follow Blue style

---

docs/src/development/development_setup.md

Update Doc mentioning blue style guide

---

ext/AvizExt/viz/rule_extraction.jl

As explained here: https://github.com/open-AIMS/ADRIA.jl/issues/474
Closes #474 .

Update viz.rules_scatter to accept targeted clusters

---

Project.toml

Update version number to 0.9.0

---

.gitignore

Add .JuliaFormatter.toml to .gitignore

---

src/Domain.jl

Update CSV.write writeheader parameter to header

---

ext/AvizExt/viz/scenarios.jl
src/analysis/scenario.jl

Rename rs_input with scenarios

---

src/io/ResultSet.jl

Add interface function to query number of scenarios in result set

---

src/analysis/analysis.jl

Analysis module was missing an include so scenario analyses were not available.

Add missing scenario analysis function definitions to analysis module

---

src/decision/dMCDA.jl
src/decision/location_selection.jl
src/scenario.jl
test/site_selection.jl

Adds functions to find depth criteria and environmental layer means which are used in location selection in `run_site_selection()` and scenario.jl.

Add functions for repeated tasks when performing location selection

---

src/ecosystem/Ecosystem.jl
src/ecosystem/corals/Corals.jl

Fix bug due to missing `default_bounds` in EnvironmentalLayer and Coral model components

---

src/Domain.jl
src/ExtInterface/ADRIA/Domain.jl
src/ExtInterface/ReefMod/Domain.jl
src/ecosystem/Ecosystem.jl
src/ecosystem/connectivity.jl
src/ecosystem/const_params.jl
src/ecosystem/waves.jl
src/interventions/Interventions.jl
src/interventions/fogging.jl
src/interventions/seeding.jl
src/io/inputs.jl

As in title. No behaviour was changed.

Apply blue styleguide to some files

---

src/decision/dMCDA.jl

Use min-max normalisation for heat stress

---

src/ecosystem/connectivity.jl

Addresses the issue we ran into @Zapiano

Handle cases where connectivity directories may be empty

---

src/ecosystem/corals/growth.jl
test/growth.jl

Fix proportional_adjustment vector conversion computational error

---

ext/AvizExt/viz/sensitivity.jl
src/analysis/sensitivity.jl
src/io/result_io.jl

Fix treatment of categorical factors in regional sensitivity analysis

---

docs/src/architecture/architecture.md

Adjust language in architectural overview to match recent changes

---

Project.toml
src/ExtInterface/ADRIA/Domain.jl
test/example_run.jl
test/runtests.jl

As in title.
Requires #598 to be merged in first, followed by a rebase onto main.

Add tests for figure creation

---

src/io/result_io.jl

Changes to dhw and wave logs to store scenario and site means and stds

---

src/analysis/rule_extraction.jl

Fix bug introduced by SIRUS v2.0.1

---

src/Domain.jl
src/ecosystem/Ecosystem.jl
src/io/inputs.jl
src/io/result_io.jl
src/io/sampling.jl
src/scenario.jl
test/sampling.jl

Fix set_factor_bounds! out of bounds for discrete factors

---

src/decision/CriteriaWeights.jl
src/ecosystem/Ecosystem.jl
src/ecosystem/corals/Corals.jl
src/factors/Factors.jl
src/interventions/Interventions.jl

As in title - create parameter types using the custom `Factor` constructor.
Of the series of PRs as indicated in #636 , merge this one first.

Update factor definitions to use custom constructor

---

src/io/ResultSet.jl
src/io/result_io.jl

Adds connectivity data to the ResultSet, as needed for #620
Closes #641

Add connectivity data to result set storage

---

src/ecosystem/corals/growth.jl
src/scenario.jl

All locations were being used as the sources to each sink. 
Larval connectivity was then being over-represented by several orders of magnitude.

Fix larval connectivity bug

---

docs/src/architecture/architecture.md
ext/AvizExt/AvizExt.jl
ext/AvizExt/viz/sensitivity.jl
src/ExtInterface/ReefMod/Domain.jl
src/decision/CriteriaWeights.jl
src/decision/location_selection.jl
src/factors/Factors.jl
src/io/sampling.jl
test/connectivity.jl
test/data_loading.jl
test/domain.jl
test/growth.jl
test/mcda.jl
test/runtests.jl
test/sampling.jl
test/seeding.jl
test/site_selection.jl
test/spec.jl

Update tests for new sampling method/factor definitions

---

src/ecosystem/corals/growth.jl

As in title.
Reverts "fix" that turned out not to be necessary, based on discussion with @Rosejoycrocker 
Includes comment from #661

Clean up settler cover function to reduce confusion

---

src/decision/CriteriaWeights.jl

Reset deployed-coral-risk-tol range

---

src/io/inputs.jl
test/io/inputs.jl

As in title.
Taking advantage of this PR to implement a constructor for YAXArrays.

Fix cyclone sorting

---

src/decision/dMCDA.jl
src/ecosystem/connectivity.jl
src/ecosystem/corals/Corals.jl
src/ecosystem/corals/growth.jl
src/interventions/seeding.jl
src/io/ResultSet.jl
src/io/inputs.jl
src/io/result_io.jl
src/scenario.jl

As in title. This one should be merged AFTER [PR 689](https://github.com/open-AIMS/ADRIA.jl/pull/689).

Switch to YAXArrays when runnin scenarios

---

src/io/inputs.jl

adding temporary utility function

added nameddimsarray2yaxarray

---

src/analysis/analysis.jl
src/analysis/clustering.jl
src/analysis/intervention.jl

The use of NamedDimsArrays in the analysis submodule is quite minimal.

Yax analysis

---

src/analysis/intervention.jl
src/io/inputs.jl
src/io/result_io.jl
src/metrics/metrics.jl
src/metrics/reef_indices.jl
src/metrics/scenario.jl
src/metrics/site_level.jl
src/metrics/temporal.jl
src/metrics/utils.jl
src/scenario.jl

Migrate the entire metrics module. All the data inside result sets that previously were saved in NamedDimsArrays is now saved in YAXArrays.
Part of #695.

Migrate metrics.jl to YAXArrays

---

src/Domain.jl
src/ExtInterface/ReefMod/RMEDomain.jl
src/decision/dMCDA.jl
src/scenario.jl
test/io/inputs.jl

Tests for ADRIA.DataCube and ADRIA.ZeroDataCube.

Yax cube tests

---

src/decision/dMCDA.jl
src/metrics/metrics.jl

Metadata was being stripped from results:

Keep metadata in results

---

src/decision/location_selection.jl

Supersedes #677 .
Tests will be updated in conjunction with all other tests.
Documentation will be updated separately.
Note the only remaining places where NamedDims are used are in the tests.
@Zapiano I've decided to leave the ranking related metrics where they are for now, as I am thinking of a larger restructure where the decision module becomes an extension package.

Finalize update of standalone MCDA methods

---

docs/src/dMCDA.md

Add high-level overview of MCDA.

Provide a succinct overview of MCDA

---

src/ExtInterface/ReefMod/ReefModDomain.jl

Add support to cyclone mortality to ReefModDomain

---

src/ExtInterface/ReefMod/RMEDomain.jl

Minor change to allow RME datasets with latest geopackage file to be loaded without issue.

Hacky support for later RME reef id list

---

src/decision/location_selection.jl

Allow user to specify a set of locations (by their IDs) to restrict assessment to.

Add support for specifying locations

---

src/metrics/ranks.jl

As in title.
Adds:
```julia
ADRIA.metrics.n_seed_locations(rs)
ADRIA.metrics.n_fog_locations(rs)
```

Additional rank methods to determine number of locations intervened on per timestep

---

src/decision/Criteria/DecisionWeights.jl
src/decision/Criteria/SeedCriteria.jl
src/factors/const_params.jl
src/io/sampling.jl

Set of minor changes, sorry for the mix of changes @DanTanAtAims, normally I'd do a single PR for each but in a crunch at the moment.

Collection of miscellaneous changes

---

src/decision/Criteria/DecisionPreferences.jl
src/decision/Criteria/SeedCriteria.jl
src/decision/location_selection.jl

Addresses error raised when specifying a minimum number of locations to select, when that minimum is greater than the number of locations that are viable/considered.

Fix bug, min. locations to select > available locations

---

src/ExtInterface/ReefMod/ReefModDomain.jl

This typo didn't change much since all locations were being selected anyway. But in the future, it could become a problem.

Fix locations selection in ReefMod datapackage cyclone mortality loading

---

src/decision/Criteria/SeedCriteria.jl
src/scenario.jl

Fix bug where locations == 0 were included when they should be excluded.

Only rank locations with available area > 0

---

docs/src/development/development_setup.md

Avoid confusion that may occur if the reader skips straight to the sub-section.

Repeat mention that the VS Code extension is being setup

---

ext/AvizExt/viz/spatial.jl
src/ecosystem/connectivity.jl

As in title.
```julia
dom = ADRIA.load_domain("<Path to Domain>")
ADRIA.viz.connectivity(dom; axis_opts=Dict(:title=>"ReefMod Engine (mean connectivity)"))
```

Convenience plotting method for connectivity/centralities

---

src/ExtInterface/ADRIA/Domain.jl
src/ecosystem/corals/CoralGrowth.jl
src/ecosystem/corals/growth.jl
src/io/result_io.jl
src/scenario.jl

Now gets all the way to the collating the metrics before erroring out.
Many methods still expect a matrix, but have added helper methods to correctly transform/reshape the data.

Changes to make use of expected multi-dimensional data structure

---

src/scenario.jl

pass available area (k_area m2) instead of total area at location.

fix initial cover block constructor

---

src/decision/location_selection.jl
src/io/inputs.jl
src/scenario.jl

Achieved by fixing scenario ids to <= 0.0
Otherwise deactivates by filling an appropriately sized data cube with 0.0 values.

Support deactivating environmental disturbances

---

src/decision/location_selection.jl

Correcting weird typo in docstrings.

Fix erroneous function call in docstrings

---

src/metrics/site_level.jl

Fix site_level dosctring

---

src/io/ResultSet.jl

Increasing compression level for slightly more manageable ResultSet sizes.

Increase compression level for ResultSet

---

.github/dependabot.yml

Recommended by https://github.com/julia-actions/setup-julia?tab=readme-ov-file#using-dependabot-version-updates-to-keep-your-github-actions-up-to-date
Note that `.github\workflows\documentation.yml` is out of date, so this will test the dependabot behavior.

julia-actions recommended dependabot.yml

---

src/scenario.jl

use `apply_mortality` instead of `apply_survival`.
Relates to [PR in CoralBlox](https://github.com/open-AIMS/CoralBlox.jl/pull/17)

use apply_mortality not apply_survival

---

src/io/result_io.jl
src/io/sampling.jl
test/sampling.jl

As in title.
Thanks to @BG-AIMS for catching this.

Fix depth min/offset being sampled for counterfactual scenarios

---

src/ADRIA.jl
src/ecosystem/corals/Corals.jl
src/ecosystem/corals/growth.jl
src/scenario.jl
src/utils/scale.jl
test/runtests.jl
test/utils/scale.jl

Also, standardize units to meters.
As in title.

Use CoralBlox linear_extension_scale_factor

---

src/ADRIA.jl
src/ecosystem/corals/Corals.jl
src/ecosystem/corals/growth.jl
src/scenario.jl
src/utils/scale.jl
test/growth.jl
test/runtests.jl
test/seeding.jl
test/utils/scale.jl

Implement linear extension scale factor

---

.github/workflows/UpdateProvenaModel.yml

Automatically produces a new version and updates the ADRIA model in provena with the GitHub hash etc of this release. 
**TODO** Update these secrets in the repo to target prod ADRIA model in provena
```
offline_token: ${{ secrets.PROVENA_PROD_TOKEN }}
domain: ${{ secrets.PROVENA_PROD_DOMAIN }}
realm_name: ${{ secrets.PROVENA_PROD_REALM_NAME }}
item_id: ${{ secrets.PROVENA_PROD_ITEM_ID }}
```
Tested on DEV and can see updated model here
Uses v0.1 release of custom action which integrates with Provena using new Python client here:
https://github.com/provena/version-update-item-action

build: prototype CD integration with Provena to update model 

---

test/sampling.jl

Fix sampling test

---

src/scenario.jl

Fix add run_model method that do not require functional_groups

---

src/ecosystem/corals/Corals.jl
src/ecosystem/corals/growth.jl

Change to `min_colony_area_full_fec`

update fecundity min area variable name for clarity

---

src/ecosystem/corals/CoralGrowth.jl

This should allow RMEDomain and ReefModDomain runs to load successfully.

fix helper dimension size error

---

src/io/cscape_result_io.jl

rename sites to locations in cscape result interface.
close #855

rename dimension from sites to locations

---

src/io/cscape_result_io.jl

Stores Scenario Id in scenario dataframe

add scenario id to scenario dataframe

---

src/ecosystem/corals/growth.jl

Under Julia v1.11, this approach allows < 12 second runtimes

Minor change for performance

---

src/interventions/seeding.jl
src/scenario.jl

Relates to issue #905.
Quick fix to prevent crashes.

Incorporate recruitment to growth constraints and cap seeding to habitable area

---

docs/Manifest.toml
docs/src/dMCDA.md
docs/src/usage/analysis.md
docs/src/usage/scenario_generation.md

When running the code of the documentation some small problem with outdated variables, preparation to run ADRIA methods and formatting were found. This PR fix this small problems. To see more details of the errors look at the commit messages.

Minor fix on docs

---

src/io/sampling.jl
test/sampling.jl

Previous implementation looped over each factor and set these individually, which is very slow.
Updated to set the factors in a single pass.
This is currently a draft as tests are needed.

Updated factor bounds setting method

---

Manifest-v1.11.toml
ext/AvizExt/viz/sensitivity.jl
src/metrics/metrics.jl
src/metrics/spatial.jl
src/spatial/spatial.jl
test/data_loading.jl
test/decisions/mcda.jl
test/domain.jl
test/runtests.jl
test/seeding.jl
test/site_selection.jl
test/spec.jl

A few tests were broken on the main branch and this PR fixes all of them - at least locally they are passing now.

Fix multiple tests

---

src/ecosystem/corals/growth.jl

Speed up by changing no heat stress threshold. 
Showing coral cover just as sanity check that this didn't change the results

Speedup bleaching

---

Project.toml

Bump project version prior to new release 

---

src/io/sampling.jl

When interventions are deactivated, all criteria factors should also be deactivated (to prevent them from being sampled, since they are not used in this case).

Deactivate criteria factors when running deactivate_interventions

---

src/ADRIA.jl
test/data/Test_domain/datapackage.json

Update compatible datapackage version to 0.8.0

---

src/io/initial_coral_cover.jl

Fix _init_cover_weights dicstring
